export const authConstants =  {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SET_LOADING: "SET_LOADING",
  SET_UNLOADING: "SET_UNLOADING",
  SET_USER: "SET_USER",
  SET_SPOTIFY_TOKEN: "SET_SPOTIFY_TOKEN"
}