export const playlistConstants = {
  ADD_PLAYLIST: "ADD_PLAYLIST",
  SET_PLAYLIST: "SET_PLAYLIST",
  REMOVE_PLAYLIST: "REMOVE_PLAYLIST",
  SET_PLAYING: "SET_PLAYING",
  SELECT_MUSIC: "SELECT_MUSIC",
  SET_ELAPSED: "SELECT_ELAPSED",
};
